name: Dockerized Go CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_test_deploy:
    runs-on: [self-hosted, windows]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Mở cổng và Chạy Bài Test
        run: |
          echo "Kiểm tra mã nguồn..."
          go test -v ./...
          
      - name: Đóng gói với Docker (Build Image)
        run: |
          echo "Bắt đầu nhồi vào Docker..."
          docker build -t my-go-app:latest .
          
      - name: Deploy chạy tự động trên Docker
        run: |
          echo "Triển khai phần mềm mới!"
          # Bước 1: Khéo léo tìm và xoá container phiên bản cũ
          try { docker rm -f my-app-running } catch { }
          
          # Bước 2: Chạy phiên bản mới nhất ở cổng 8080 dạng chạy ngầm (-d)
          docker run -d --name my-app-running -p 8080:8080 my-go-app:latest
          
          echo "Ứng dụng Docker đã được triển khai xong trên cổng 8080!"
